version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: erensekkeli
      POSTGRES_PASSWORD: 123456789
      POSTGRES_DB: n11-company-service
    volumes:
      - data-volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  companyservice:
    build:
      context: ./CompanyService
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/n11-company-service
      SPRING_DATASOURCE_USERNAME: erensekkeli
      SPRING_DATASOURCE_PASSWORD: 123456789
    depends_on:
      - postgres

  customerreviewservice:
    build:
      context: ./CustomerReviewService
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/n11-customer-service
      SPRING_DATASOURCE_USERNAME: erensekkeli
      SPRING_DATASOURCE_PASSWORD: 123456789
    depends_on:
      - postgres

volumes:
  data-volume: