version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: erensekkeli
      POSTGRES_PASSWORD: 123456789
    volumes:
      - postgre_db:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5433:5432"

  companyservice:
    build:
      context: ./CompanyService
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - solr

  customerreviewservice:
    build:
      context: ./CustomerReviewService
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  solr:
    image: solr:latest
    container_name: n11_solr
    ports:
      - "8983:8983"
    volumes:
      - ./solrdata:/var/solr
    command:
      - solr-precreate
      - company

volumes:
  postgre_db:
    driver: local
  solrdata: